#ifndef CORE_MQTT_AGENT_CONFIG_H
#define CORE_MQTT_AGENT_CONFIG_H

#include "sdkconfig.h"

#define MQTT_AGENT_MAX_EVENT_QUEUE_WAIT_TIME       ( CONFIG_MQTT_AGENT_MAX_EVENT_QUEUE_WAIT_TIME )
#define MQTT_AGENT_MAX_OUTSTANDING_ACKS            ( CONFIG_MQTT_AGENT_MAX_OUTSTANDING_ACKS )

#endif /* CORE_MQTT_AGENT_CONFIG_H */
